# Generated by Django 3.2.12 on 2022-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Author', models.CharField(default='Subrata Kr Paul', max_length=255)),
                ('Title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(max_length=4000)),
                ('picture', models.FileField(upload_to='uploads')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
