# Generated by Django 3.2.12 on 2022-12-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221207_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uploaded_date',
            field=models.DateTimeField(),
        ),
    ]
